/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as OnboardingSourceRouteImport } from './routes/onboarding.source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSourceRoute = OnboardingSourceRouteImport.update({
  id: '/onboarding/source',
  path: '/onboarding/source',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/api/chat'
    | '/onboarding/goal'
    | '/onboarding/role'
    | '/onboarding/source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/api/chat'
    | '/onboarding/goal'
    | '/onboarding/role'
    | '/onboarding/source'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/api/chat'
    | '/onboarding/goal'
    | '/onboarding/role'
    | '/onboarding/source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingSourceRoute: typeof OnboardingSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/source': {
      id: '/onboarding/source'
      path: '/onboarding/source'
      fullPath: '/onboarding/source'
      preLoaderRoute: typeof OnboardingSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingSourceRoute: OnboardingSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
